### ISSUE TITLE
Site doesn't load due to certificate error

### ISSUE THREAD

**Issue by cvrebert** [whatwg/platform.html5.org#45]
From the Firefox error message:

> platform.html5.org uses an invalid security certificate.
> The certificate is not trusted because it is self-signed.
> The certificate is not valid for the name platform.html5.org.

**Comment by annevk** [comment]
Thanks for reporting. Just pinged DreamHost again. 😟

**Comment by cvrebert** [comment]
This seems to be fixed now. 😄

**Comment by annevk** [comment]
Yeah, sorry, forgot to close this. There was a recent server move and apparently some of the Let's Encrypt logic was left behind...
