### ISSUE TITLE
Add some new specs?

### ISSUE THREAD

**Issue by xfq** [whatwg/platform.html5.org#46]
Some examples:

* [CSS Containment](https://drafts.csswg.org/css-contain/)
* [CSS Timing Functions](https://drafts.csswg.org/css-timing/)?
* [Infra](https://infra.spec.whatwg.org/)?
* Maybe some a11y-related specifications (I only found ARIA under the "HTML bonus features" section)

**Comment by annevk** [comment]
Infra is probably not super useful for developers, but the others seem worth mentioning. Feel free to submit a pull request.

**Comment by xfq** [comment]
Will submit PR later.
