### ISSUE TITLE
(proposal): develop a new type of "service worker" that runs sandboxed native code packaged as a (docker-like) container

### ISSUE THREAD

**Issue by les2** [whatwg/platform.html5.org#48]
# summary

The author proposes that a containerization technology (like docker) be developed for use as service workers on the web platform. The author anticipates that many new types of applications that were once infeasible would be enabled by providing such a container technology as part of the web platform.

Note: This document is not a detailed technical proposal. It's intent it to spark conversion on the feasibility and wisdom of implementing the capability loosely described in this document. The author fully expects that this issue will be closed without further word because he is relatively unknown and because people's immediate reaction will be "face palm; docker again?".

# security considerations

- The container would be subject to the same networking restrictions as ordinary service works and web technologies, that is, the same origin principle would apply.
- The container must be sufficiently sandboxed so that running its untrusted, native code could do no more harm that an equivalent JavaScript program. I believe that containers today offer sufficient isolation so as to make this feasible.
- The container must be prevented from consuming too many resources. cpu, memory, networking and other quotas supported by container technology can easily be used to ensure that the users entire system is no more affected by the container than by an equivalently resource hogging JavaScript service worker.
- The browsers interaction with the containers filesystem should be enabled by carefully developed, secure APIs. It should be possible for containers to generate files (e.g., images, Excel documents, etc.) for download by the user.

# communication with the container

JavaScript running in the browser would interact with the container using techniques largely similar to those used for communicating with service workers.

Additional APIs should be available for efficiently and safely sharing other resources provided by the container.

**Comment by annevk** [comment]
If you want to run native code, the answer is compiling it down to https://github.com/WebAssembly. Also, a better place for this kind of discussion is https://discourse.wicg.io/ or some such.
