### ISSUE TITLE
SSL connection error.

### ISSUE THREAD

**Issue by jayzamazing** [whatwg/platform.html5.org#49]
Can't view the web site due to an the following ssl connection error: An error occurred during a connection to platform.html5.org. SSL received a record that exceeded the maximum permissible length. Error code: SSL_ERROR_RX_RECORD_TOO_LONG. I tried this using safari, chrome, and firefox.

**Comment by zcorpan** [comment]
I can't reproduce this.

**Comment by domenic** [comment]
Interesting, myself and @zcorpan tested and are getting no problems in any of our browsers.

Can you try from a different network, e.g. your mobile phone? It seems plausible you're behind some kind of software that's misconfigured, e.g. a corporate proxy.

**Comment by jayzamazing** [comment]
I will give it a try later tonight when I get home. I just tested it off my works connection and a comcast connection with the same result.

**Comment by sideshowbarker** [comment]
What browsers have you tried and which ones are you seeing this problem in? 

https://support.mozilla.org/en-US/questions/976504 suggests maybe the cause is related to the SSL/TLS version your browser(s) is configured to use

**Comment by jayzamazing** [comment]
I believe this issue has to do with Sophos AV. Seems to work when I disable it. I think this issue can be closed.
